### ISSUE TITLE
Correct footer credits text

### ISSUE THREAD

**Issue by samakintunde** [snack-ui/snack#7]
Footer credits at the bottom of the docs' site reads "... ❤️ Made with using snack". I'm guessing that should be "...Made with ❤️ using snack"
<img width="501" alt="Screen_Shot_footer" src="https://user-images.githubusercontent.com/29522778/119546977-6dcaa400-bd8c-11eb-90ba-a41aae041e5e.png">

**Comment by nzbin** [comment]
Many thanks, I have fixed it.
